version: "3.8"

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bot-backend
    ports:
      - "5432:5432" # чек, на то, занят ли порт


  redis:
    image: redis:7
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    command: "redis-server --save 20 1 --loglevel warning"

  bot:
    build: .
    command: "python main.py"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/usr/src/app


volumes:
  postgres_data:
  redis_data:
